name: Android CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  fast-check:
    name: Fast native check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set ANDROID_SDK_ROOT
        run: echo "ANDROID_SDK_ROOT=$RUNNER_TEMP/android-sdk" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install minimal Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d cmdline
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv cmdline/cmdline-tools/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
          rm -rf cmdline cmdline.zip
          # expose sdkmanager and platform-tools for following steps
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses || true
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-35" "build-tools;34.0.0"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Fast Kotlin compile check
        working-directory: android
        run: |
          chmod +x ./gradlew || true
          ./gradlew :react-native-gesture-handler:compileDebugKotlin :expo-modules-core:compileDebugKotlin --no-daemon --stacktrace

  build:
    runs-on: ubuntu-latest
    needs: fast-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set ANDROID_SDK_ROOT
        run: echo "ANDROID_SDK_ROOT=$RUNNER_TEMP/android-sdk" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          unzip -q cmdline.zip -d cmdline
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv cmdline/cmdline-tools/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
          rm -rf cmdline cmdline.zip
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses || true
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-35" "build-tools;34.0.0" "cmake;3.22.1" "ndk;25.1.8937393"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install node modules
        working-directory: .
        run: |
          npm ci

      - name: Build debug APK
        working-directory: android
        run: |
          chmod +x ./gradlew || true
          ./gradlew assembleDebug --no-daemon --stacktrace
      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/**/*.apk
